version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:715451173743:task-definition/helloapp-defe:1"
        LoadBalancerInfo:
          ContainerName: "helloapp-container"
          ContainerPort: 80
        PlatformVersion: "LATEST"
