version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=715451173743.dkr.ecr.ap-northeast-1.amazonaws.com/helloapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build -t $REPOSITORY_URI:latest .
      - make ENV=PROD build-container
      - docker tag helloapp:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag helloapp:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 715451173743.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      # - echo Writing image definitions file...
      # - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#     files: imagedefinitions.json